### ISSUE TITLE
Lab 3 Bring you own container: Dependency issues with Pandas/Numpy

### ISSUE THREAD

**Issue by Yang-sunny** [aws-samples/amazon-sagemaker-immersion-day#95]
Hi team,

The training code within [scikit_bring_your_own.zip](https://github.com/aws-samples/amazon-sagemaker-immersion-day/blob/master/bring-your-own-model/scikit_bring_your_own.zip) is build with Numpy < 2.0.0 in mind.

During training this gives out a dependency error.

Fix is to update the Dockerfile within scikit_bring_your_own.zip to add Numpy==1.x.x runing the pip install step

Regards

**Comment by pdifranc** [comment]
Thanks for the heads up @Yang-sunny. just saw numpy v2 was recently released.

**Comment by pdifranc** [comment]
Fixed #96
